version: '3.8'

services:

  app_1:
    container_name: app_1
    build: .
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    restart: always

  app_2:
    container_name: app_2
    build: .
    environment:
      - PORT=3000
    ports:
      - '3001:3000'
    restart: always

  app_3:
    container_name: app_3
    build: .
    environment:
      - PORT=3000
    ports:
      - '3002:3000'
    restart: always

  nginx:
    image: nginx
    depends_on:
      - app_1
      - app_2
      - app_3
    ports:
      - '8000:8000'
    restart: always